sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

install:
  - mvn -s configuration/settings.xml clean install

script:
  - mvn -s configuration/settings.xml test

jdk:
  - oraclejdk8

notifications:
  email: false
